-- Create database
CREATE DATABASE travelcompany;

USE travelcompany;


-- Create tables
CREATE TABLE Hotel (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL,
	Stars INT CHECK(Stars BETWEEN 1 AND 5) NOT NULL,
	City NVARCHAR(50) NOT NULL,
	Available BIT NOT NULL
);

CREATE TABLE Currency (
	Code VARCHAR(3) PRIMARY KEY CHECK (Code In ('USD','COP','EUR'))
);

INSERT INTO Currency VALUES ('USD'), ('COP'), ('EUR');

CREATE TABLE RoomType (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(10) UNIQUE NOT NULL,
);

INSERT INTO RoomType VALUES ('JUNIOR'), ('DOUBLE'), ('TRIPLE'), ('EXECUTIVE');

CREATE TABLE Room (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	HotelId INT NOT NULL,
	RoomTypeId INT NOT NULL, 
	Capacity INT NOT NULL,
	Rate DECIMAL(10,2) NOT NULL,
	Tax DECIMAL(10,2) NOT NULL,
	CurrencyCode VARCHAR(3) NOT NULL,
	Floor INT NOT NULL,
	Available BIT NOT NULL,
	CONSTRAINT FK_RoomHotel FOREIGN KEY (HotelId) REFERENCES Hotel(Id) ON DELETE CASCADE,
    CONSTRAINT FK_RoomRoomType FOREIGN KEY (RoomTypeId) REFERENCES RoomType(Id),
    CONSTRAINT FK_RoomCurrency FOREIGN KEY (CurrencyCode) REFERENCES Currency(Code)
);

CREATE TABLE Guest (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	BirthDate DATE NOT NULL,
	Gender NVARCHAR(6) CHECK (Gender IN ('MALE', 'FEMALE', 'OTHER')),
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Phone NVARCHAR(15) NOT NULL,
	IdentityType NVARCHAR(10) CHECK (IdentityType IN ('DNI', 'CC', 'PASSPORT')) NOT NULL,
	IdentityNumber NVARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Booking (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CheckIn DATE NOT NULL,
	CheckOut DATE NOT NULL,
	Guests INT NOT NULL,
	HotelId INT NOT NULL,
	EmergencyContactName NVARCHAR(40) NOT NULL,
	EmergencyContactPhone NVARCHAR(15) NOT NULL,
	CONSTRAINT FK_BookingHotel FOREIGN KEY (HotelId) REFERENCES Hotel(Id) ON DELETE CASCADE,
);

CREATE TABLE BookingRoom (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	BookingId INT NOT NULL,
	RoomId INT NOT NULL,
	CONSTRAINT FK_BookingRoomBooking FOREIGN KEY (BookingId) REFERENCES Booking(Id) ON DELETE CASCADE,
	CONSTRAINT FK_BookingRoomRoom FOREIGN KEY (RoomId) REFERENCES Room(Id)
);

CREATE TABLE BookingGuest (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	BookingId INT NOT NULL,
	GuestId INT NOT NULL,
	CONSTRAINT FK_BookingGuestBooking FOREIGN KEY (BookingId) REFERENCES Booking(Id) ON DELETE CASCADE,
	CONSTRAINT FK_BookingGuestGuest FOREIGN KEY (GuestId) REFERENCES Guest(Id)
);

